### ISSUE TITLE
Can't create contributors file

### ISSUE THREAD

**Issue by samuelfernandez** [bubkoo/contributors-list-action#4]
### Expected Behavior

It creates the svg file in the repo

### Current Behavior

The creation of the contributors svg fails

### Steps To Reproduce

https://github.com/ng-easy/platform/runs/7371097328?check_suite_focus=true

<details><summary>Error Message & Stack Trace</summary><p>

```txt
Error: HttpError: Could not create file: 4 of 4 required status checks are expected.
```

</p></details>

### Additional Context

![image](https://user-images.githubusercontent.com/19343955/179358960-6be0db62-f3ca-4bfc-802a-0e65cfe5fafd.png)

### Your Environment

GitHub workflow

**Comment by jrson83** [comment]
@samuelfernandez check the branch protection rules of your repository. I had almost the same issue, when I created a branch protection rule. I think the right way to fix is using [permissions](https://docs.github.com/en/actions/using-jobs/assigning-permissions-to-jobs) inside the workflow.

**Comment by samuelfernandez** [comment]
@jrson83 Thanks for the reply. Any example of the permissions configuration? Or would you know which one exactly is needed?

**Comment by jrson83** [comment]
@samuelfernandez give me a minute, I just saw my workflow failed again. I will reply when I know how to fix it :grin:

**Comment by jrson83** [comment]
hmm I don't know. This action just uses commit and has just one option `noCommit` to disable commit. Since there is no option to create a PR, I don't know if this is possible. I tried something like this, but I just get the error:

`Error: HttpError: Could not update file: Changes must be made through a pull request.`

The only rule I have set is `Require a pull request before merging` and I have enabled actions to create and approve pull requests.
@wow-actions, do you know a solution?

**Comment by jrson83** [comment]
@samuelfernandez I got it working by setting the option `noCommit: true` and then run [peter-evans/create-pull-request](https://github.com/peter-evans/create-pull-request/) action. Here is the complete action:

```yaml
name: Contributors List

on:
  workflow_dispatch:
  
  schedule:
    - cron: "0 3 */2 * *"

jobs:
  contributors:
    permissions:
      contents: write
      pull-requests: write

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@8f4b7f84864484a7bf31766abe9204da3cbe65b3 # v3.5.0
        with:
          fetch-depth: 0
          ref: ${{ github.event.repository.default_branch }}
          
      - name: Update contributors list
        uses: wow-actions/contributors-list@b9e91f91a51a55460fdcae64daad0cb8122cdd53 # v1.1.0
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          svgPath: .github/assets/CONTRIBUTORS.svg
          round: true
          includeBots: false
          noCommit: true
      
      - name: Commit & PR
        uses: peter-evans/create-pull-request@38e0b6e68b4c852a5500a94740f0e535e0d7ba54 # v4.2.4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          add-paths: .github/assets/CONTRIBUTORS.svg
          commit-message: 'chore(): update contributors-list'
          committer: GitHub <noreply@github.com>
          author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          signoff: false
          branch: workflow/update-contributors-list
          base: main
          delete-branch: true
          title: 'chore(): update contributors-list'
          body: |
            Automated update to `.github/assets/CONTRIBUTORS.svg`
```
